FROM amazonlinux:latest

# Install dependencies
RUN yum update -y && \
    yum install -y httpd && \
    yum search wget && \
    yum install wget -y && \
    yum install unzip -y

# change directory
RUN cd /var/www/html

# download webfiles
RUN wget https://codeload.github.com/manojastro/portfoliomanoj/zip/refs/heads/master


# unzip folder
RUN unzip portfoliomanoj-master.zip

# copy files into html directory
RUN cp -r portfoliomanoj-master/* /var/www/html/

# exposes port 80 on the container
EXPOSE 80

# set the default application that will start when the container start
ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]